[package]
name = "home_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
mlua = { version = "0.10.3", features = ["lua51", "vendored"] }
